### ISSUE TITLE
Add option to enable cloudwatch logging

### ISSUE THREAD

**Issue by hypexr** [serverless-components/graphql#5]
It seems that by default the lambda deployed by graphql has it's logs captured and sent to serverless and they don't show up in the cloudwatch console.

It would be ideal if there was a way to configure it to also log to cloudwatch.

**Comment by harleyguru** [comment]
AppSync deployed by this component didn't enable the logging of AppSync service.

**Comment by hypexr** [comment]
My issue was about a different issue with the lambda logs now showing up in cloudwatch, but I haven't encountered this issue since so I'm going to close this one.

@harleyguru Please create a new issue for the appsync logging issue.
